name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - arviz=0.11.2
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cftime=1.6.0
  - colorama=0.4.4
  - convertdate=2.4.0
  - curl=7.82.0
  - cycler=0.11.0
  - cython=0.29.28
  - ephem=4.1.3
  - fbprophet=0.7.1
  - fonttools=4.30.0
  - freetype=2.10.4
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - giflib=5.2.1
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hijri-converter=2.2.3
  - holidays=0.13
  - importlib-metadata=4.11.2
  - importlib_metadata=4.11.2
  - jbig=2.1
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - korean_lunar_calendar=0.2.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzip=1.8.0
  - libzlib=1.2.11
  - lunarcalendar=0.0.9
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.5.8
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.3
  - pandas=1.4.1
  - pillow=9.0.1
  - pip=22.0.4
  - pthread-stubs=0.4
  - pymeeus=0.5.10
  - pyparsing=3.0.7
  - pystan=2.19.1.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - readline=8.1
  - scipy=1.8.0
  - setuptools=60.9.3
  - six=1.16.0
  - sqlite=3.37.0
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tqdm=4.63.0
  - typing_extensions=4.1.1
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xarray=2022.3.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - alembic==1.7.6
    - anyio==3.5.0
    - apache-airflow==2.2.4
    - apache-airflow-providers-ftp==2.1.0
    - apache-airflow-providers-http==2.1.0
    - apache-airflow-providers-imap==2.2.1
    - apache-airflow-providers-sqlite==2.1.1
    - apispec==3.3.2
    - argcomplete==2.0.0
    - attrs==20.3.0
    - babel==2.9.1
    - blinker==1.4
    - cachelib==0.6.0
    - cattrs==1.10.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==7.1.2
    - clickclick==20.10.2
    - colorlog==6.6.0
    - commonmark==0.9.1
    - connexion==2.12.0
    - croniter==1.3.4
    - cryptography==36.0.1
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - dill==0.3.4
    - dnspython==2.2.1
    - docutils==0.16
    - email-validator==1.1.3
    - flask==1.1.4
    - flask-appbuilder==3.4.4
    - flask-babel==2.0.0
    - flask-caching==1.10.1
    - flask-jwt-extended==3.25.1
    - flask-login==0.4.1
    - flask-openid==1.3.0
    - flask-session==0.4.0
    - flask-sqlalchemy==2.5.1
    - flask-wtf==0.14.3
    - gunicorn==20.1.0
    - h11==0.12.0
    - httpcore==0.14.7
    - httpx==0.22.0
    - idna==3.3
    - importlib-resources==5.4.0
    - inflection==0.5.1
    - iso8601==1.0.2
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - lazy-object-proxy==1.7.1
    - lockfile==0.12.2
    - mako==1.2.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - marshmallow==3.14.1
    - marshmallow-enum==1.5.1
    - marshmallow-oneofschema==3.0.1
    - marshmallow-sqlalchemy==0.26.1
    - pendulum==2.1.2
    - prison==0.2.1
    - psutil==5.9.0
    - pycparser==2.21
    - pygments==2.11.2
    - pyjwt==1.7.1
    - pyrsistent==0.18.1
    - python-daemon==2.3.0
    - python-nvd3==0.15.0
    - python-slugify==4.0.1
    - python3-openid==3.2.0
    - pytzdata==2020.1
    - pyyaml==5.4.1
    - requests==2.27.1
    - rfc3986==1.5.0
    - rich==12.0.0
    - setproctitle==1.2.2
    - sniffio==1.2.0
    - sqlalchemy==1.3.24
    - sqlalchemy-jsonfield==1.0.0
    - sqlalchemy-utils==0.38.2
    - swagger-ui-bundle==0.0.9
    - tabulate==0.8.9
    - tenacity==8.0.1
    - termcolor==1.1.0
    - text-unidecode==1.3
    - unicodecsv==0.14.1
    - urllib3==1.26.8
    - werkzeug==1.0.1
    - wrapt==1.14.0
    - wtforms==2.3.3
    - xgboost==1.5.2

